FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base

WORKDIR /app
EXPOSE 8080

EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0-nanoserver-1809 AS build

ARG BUILD_CONFIGURATION=Release

WORKDIR /src

COPY ["YarpLoadBalancer/YarpLoadBalancer.csproj", "YarpLoadBalancer/"]

RUN dotnet restore "./YarpLoadBalancer/YarpLoadBalancer.csproj"

COPY . .

WORKDIR "/src/YarpLoadBalancer"

RUN dotnet build "./YarpLoadBalancer.csproj" -c %BUILD_CONFIGURATION% -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "./YarpLoadBalancer.csproj" -c %BUILD_CONFIGURATION% -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "YarpLoadBalancer.dll"]